feature_extraction:
    name: ShennongFilterbank
    params:
        e: True
        fftWindow: 'hanning'
        melLowFreq: 20
        melHighFreq: 0
        melNbFilters: 40
        pitchFmin: 20
        pitchFmax: 500
        with_pitch: True
        duration: 0.025
        step: 0.010
        sample_rate: 16000
