feature_extraction:
    name: ShennongMfcc
    params:
        coefs: 13
        e: True
        D: True
        DD: True
        mfcc_window_type: 'hanning'
        mfcc_low_freq: 20
        mfcc_high_freq: -100 # Real value will be (f_nyquist - 100)
        with_pitch: True
        with_cmvn: True
        duration: 0.025
        step: 0.010
        sample_rate: 16000
        fmin: 20
        fmax: 500
